version: '3.4'

# docker-compose build && docker-compose down && docker-compose up --detach && docker-compose ps

services:
  nginx-reverse:
    container_name: nginx-reverse
    hostname: nginx-reverse
    build:
      context: .
      dockerfile: Dockerfile-nginx-reverse
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-reverse/html:/usr/share/nginx/html
      - ./nginx-reverse/conf.d:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 0m15s
      timeout: 10s
      retries: 3
      start_period: 40s
  php-apache:
    container_name: php-apache
    hostname: php-apache
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    restart: always
    ports:
      - 9001:80
      - 9002:443
    volumes:
      - ./php-apache/html:/var/www/html
      - ./php-apache/php.ini:/usr/local/etc/php/php.ini
      - ./php-apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./php-apache/ssl.conf:/etc/apache2/mods-available/ssl.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/php-apache/"]
      interval: 0m15s
      timeout: 10s
      retries: 3
      start_period: 40s
  php-nginx:
    container_name: php-nginx
    hostname: php-nginx
    build:
      context: .
      dockerfile: Dockerfile-php-nginx
    restart: always
    ports:
      - 9003:80
      - 9004:443
    volumes:
      - ./php-nginx/html:/usr/share/nginx/html
      - ./php-nginx/php.ini:/usr/local/etc/php/php.ini
      - ./php-nginx/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/php-nginx/"]
      interval: 0m15s
      timeout: 10s
      retries: 3
      start_period: 40s
  # https://hub.docker.com/r/willfarrell/autoheal/
  autoheal:
    restart: always
    image: willfarrell/autoheal:v0.7.0
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
