# https://docs.docker.com/samples/library/nginx/
FROM nginx:1.15.11

RUN apt update && apt install -y lsof vim openssl curl netcat iputils-ping dnsutils

RUN mkdir -p /etc/ssl/certs /etc/ssl/private
RUN openssl req -subj '/CN=example.com/O=Example Company/C=UK' -new -newkey rsa:2048 -sha256 -days 3650 -nodes -x509 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt
RUN cat /etc/ssl/certs/server.crt /etc/ssl/private/server.key > /etc/ssl/certs/server.pem
